name: crypto_concept
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  flutter_gen_runner:

flutter_gen:
  output: lib/src/core/presentation/generated/

flutter:
  uses-material-design: true
  shaders:
    - assets/shaders/atmospheric_scattering.frag
    - assets/shaders/bubble_ring.frag
    - assets/shaders/spherical_polyhedra.frag
    - assets/shaders/neon_lines.frag
  fonts:
    - family: GMarketSans
      fonts:
        - asset: assets/fonts/gmarket_sans/GmarketSansBold.otf
          weight: 700
        - asset: assets/fonts/gmarket_sans/GmarketSansMedium.otf
          weight: 500
        - asset: assets/fonts/gmarket_sans/GmarketSansLight.otf
          weight: 300
