name: Style
description: Changes that do not affect the meaning of the code (white space, formatting, missing semi-colons, etc)
title: "[Style] "
labels: ["style"]
body:
- type: textarea
  attributes:
    label: Description
    description: 무엇을 바꿀 것이고, 왜 바꿔야하는지 설명해주세요.
    placeholder: |
      1. Class 명칭은 CamelCase 방식으로 작성되어야 합니다.
      2. ...
  validations:
    required: true
- type: textarea
  attributes:
    label: Requirements
    description: 이 이슈를 해결 할 때 제약 사항을 적어 주세요, 그 제약 사항을 지키면서 이슈를 해결해야 합니다.
    placeholder: |
      1. Test Coverage가 떨어지지 않아야 합니다.
      2. ...
  validations:
 
